#!/usr/bin/env python3
"""Writes app/src/gui/glissando/LandMask.h, the land and sea the console's
map ball is painted from.

The source is Natural Earth's 1:110m countries (public domain,
https://www.naturalearthdata.com/), as geopandas 0.14 ships it in
geopandas/datasets/naturalearth_lowres/naturalearth_lowres.shp; any copy of
ne_110m_admin_0_countries.shp or ne_110m_land.shp will do. Only the standard
library is needed:

    python3 prototype/globe/gen_land_mask.py path/to/naturalearth_lowres.shp --write

The mask is equirectangular, CELLS_PER_DEGREE cells to a degree, the top row
at 90 N and the first column at 180 W. A cell is land when its centre falls
inside a country. Each row is stored as run lengths, sea first.
"""

import argparse
import os
import struct
import sys

CELLS_PER_DEGREE = 4
WIDTH = 360 * CELLS_PER_DEGREE
HEIGHT = 180 * CELLS_PER_DEGREE

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "..", "app", "src", "gui", "glissando", "LandMask.h")


def read_polygons(path):
    """Every polygon record's rings, as lists of (lon, lat)."""
    with open(path, "rb") as f:
        data = f.read()
    shapes = []
    pos = 100
    while pos < len(data):
        _, length = struct.unpack(">ii", data[pos:pos + 8])
        content = data[pos + 8:pos + 8 + 2 * length]
        pos += 8 + 2 * length
        shape_type = struct.unpack("<i", content[:4])[0]
        if shape_type not in (5, 15, 25):
            continue
        num_parts, num_points = struct.unpack("<ii", content[36:44])
        parts = list(struct.unpack("<%di" % num_parts, content[44:44 + 4 * num_parts]))
        offset = 44 + 4 * num_parts
        points = [struct.unpack("<dd", content[offset + 16 * i:offset + 16 * i + 16])
                  for i in range(num_points)]
        parts.append(num_points)
        shapes.append([points[parts[i]:parts[i + 1]] for i in range(num_parts)])
    return shapes


def rasterize(shapes):
    rows = [bytearray(WIDTH) for _ in range(HEIGHT)]
    for rings in shapes:
        edges = []
        for ring in rings:
            for (x0, y0), (x1, y1) in zip(ring, ring[1:] + ring[:1]):
                if y0 != y1:
                    edges.append((x0, y0, x1, y1))
        lats = [y for ring in rings for _, y in ring]
        top = max(0, int((90.0 - max(lats)) * CELLS_PER_DEGREE))
        bottom = min(HEIGHT - 1, int((90.0 - min(lats)) * CELLS_PER_DEGREE) + 1)
        for row in range(top, bottom + 1):
            lat = 90.0 - (row + 0.5) / CELLS_PER_DEGREE
            crossings = []
            for x0, y0, x1, y1 in edges:
                if (y0 <= lat < y1) or (y1 <= lat < y0):
                    crossings.append(x0 + (lat - y0) * (x1 - x0) / (y1 - y0))
            crossings.sort()
            # Even-odd within a country, so its holes (Lesotho in South
            # Africa) stay holes; countries are or'ed together.
            for a, b in zip(crossings[0::2], crossings[1::2]):
                first = max(0, int(round((a + 180.0) * CELLS_PER_DEGREE - 0.5)))
                last = min(WIDTH - 1, int(round((b + 180.0) * CELLS_PER_DEGREE - 0.5)) - 1)
                for column in range(first, last + 1):
                    rows[row][column] = 1
    return rows


def runs_of(row):
    runs = []
    value = 0
    count = 0
    for cell in row:
        if cell == value:
            count += 1
        else:
            runs.append(count)
            value = cell
            count = 1
    runs.append(count)
    return runs


def header(rows):
    all_runs = []
    starts = []
    for row in rows:
        starts.append(len(all_runs))
        all_runs.extend(runs_of(row))
    starts.append(len(all_runs))

    def wrap(values, per_line):
        lines = []
        for i in range(0, len(values), per_line):
            lines.append("    " + ", ".join(str(v) for v in values[i:i + per_line]) + ",")
        return "\n".join(lines)

    land = sum(sum(row) for row in rows)
    return f"""//=========================================================================
// Name:            LandMask.h
// Purpose:         Land and sea for the console's map ball. Generated by
//                  prototype/globe/gen_land_mask.py from Natural Earth's
//                  1:110m countries (public domain); do not edit by hand.
//
// Equirectangular, {CELLS_PER_DEGREE} cells to a degree: row 0 is at 90 N, column 0 at
// 180 W. Row r is LAND_RUNS[LAND_ROW_START[r]] up to LAND_ROW_START[r + 1],
// run lengths alternating sea and land, sea first. {100.0 * land / (WIDTH * HEIGHT):.1f} % of cells are land.
//=========================================================================

#ifndef GUI_GLISSANDO__LAND_MASK_H
#define GUI_GLISSANDO__LAND_MASK_H

#include <cstdint>

namespace LandMask
{{

constexpr int CELLS_PER_DEGREE = {CELLS_PER_DEGREE};
constexpr int WIDTH = {WIDTH};
constexpr int HEIGHT = {HEIGHT};

constexpr uint32_t LAND_ROW_START[HEIGHT + 1] = {{
{wrap(starts, 12)}
}};

constexpr uint16_t LAND_RUNS[] = {{
{wrap(all_runs, 16)}
}};

}} // namespace LandMask

#endif // GUI_GLISSANDO__LAND_MASK_H
"""


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("shapefile")
    parser.add_argument("--write", action="store_true", help="write LandMask.h rather than report")
    args = parser.parse_args()

    rows = rasterize(read_polygons(args.shapefile))
    text = header(rows)
    runs = sum(len(runs_of(row)) for row in rows)
    print(f"{WIDTH} x {HEIGHT} cells, {runs} runs, {len(text)} bytes of header", file=sys.stderr)
    if args.write:
        with open(OUT, "w") as f:
            f.write(text)
        print(f"wrote {os.path.normpath(OUT)}", file=sys.stderr)


if __name__ == "__main__":
    main()
