#!/usr/bin/env python3
"""Writes app/src/gui/glissando/LandOutlines.h, the coastlines the console's
map ball is drawn from.

The source is Natural Earth's 1:110m countries (public domain,
https://www.naturalearthdata.com/), as geopandas 0.14 ships it in
geopandas/datasets/naturalearth_lowres/naturalearth_lowres.shp; any copy of
ne_110m_admin_0_countries.shp or ne_110m_land.shp will do. Only the standard
library is needed:

    python3 prototype/globe/gen_land_outlines.py path/to/naturalearth_lowres.shp --write

Each ring of each country is kept as the shapefile has it: outlines of land
clockwise, holes in it (Lesotho in South Africa) anticlockwise, longitude
east and latitude north. Edges longer than MAX_EDGE_DEGREES are split, so
that drawn as great circles they still follow the map's straight lines. The
points go in hundredths of a degree.
"""

import argparse
import math
import os
import struct
import sys

MAX_EDGE_DEGREES = 2.0
SCALE = 100

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "..", "app", "src", "gui", "glissando", "LandOutlines.h")


def read_rings(path):
    """Every polygon's rings, as lists of (lon, lat), the closing point dropped."""
    with open(path, "rb") as f:
        data = f.read()
    rings = []
    pos = 100
    while pos < len(data):
        _, length = struct.unpack(">ii", data[pos:pos + 8])
        content = data[pos + 8:pos + 8 + 2 * length]
        pos += 8 + 2 * length
        shape_type = struct.unpack("<i", content[:4])[0]
        if shape_type not in (5, 15, 25):
            continue
        num_parts, num_points = struct.unpack("<ii", content[36:44])
        parts = list(struct.unpack("<%di" % num_parts, content[44:44 + 4 * num_parts]))
        offset = 44 + 4 * num_parts
        points = [struct.unpack("<dd", content[offset + 16 * i:offset + 16 * i + 16])
                  for i in range(num_points)]
        parts.append(num_points)
        for i in range(num_parts):
            ring = points[parts[i]:parts[i + 1]]
            if len(ring) > 1 and ring[0] == ring[-1]:
                ring = ring[:-1]
            if len(ring) >= 3:
                rings.append(ring)
    return rings


def densified(ring):
    """The ring with long edges split; edges along a pole are left alone."""
    out = []
    for (x0, y0), (x1, y1) in zip(ring, ring[1:] + ring[:1]):
        out.append((x0, y0))
        if abs(y0) == 90.0 and y0 == y1:
            continue
        pieces = math.ceil(max(abs(x1 - x0), abs(y1 - y0)) / MAX_EDGE_DEGREES)
        for k in range(1, pieces):
            t = k / pieces
            out.append((x0 + (x1 - x0) * t, y0 + (y1 - y0) * t))
    return out


def signed_area(ring):
    return sum(x0 * y1 - x1 * y0 for (x0, y0), (x1, y1) in zip(ring, ring[1:] + ring[:1])) / 2.0


def header(rings):
    starts = []
    values = []
    for ring in rings:
        starts.append(len(values) // 2)
        for lon, lat in ring:
            values.append(int(round(lon * SCALE)))
            values.append(int(round(lat * SCALE)))
    starts.append(len(values) // 2)
    holes = sum(1 for ring in rings if signed_area(ring) > 0)

    def wrap(numbers, per_line):
        lines = []
        for i in range(0, len(numbers), per_line):
            lines.append("    " + ", ".join(str(v) for v in numbers[i:i + per_line]) + ",")
        return "\n".join(lines)

    return f"""//=========================================================================
// Name:            LandOutlines.h
// Purpose:         The coastlines of the console's map ball. Generated by
//                  prototype/globe/gen_land_outlines.py from Natural Earth's
//                  1:110m countries (public domain); do not edit by hand.
//
// {len(rings)} rings, {holes} of them holes. Ring r is POINTS[RING_START[r]] up to
// RING_START[r + 1], each point a longitude then a latitude in hundredths
// of a degree. Land is outlined clockwise (east right, north up), a hole
// anticlockwise; the last point joins back to the first.
//=========================================================================

#ifndef GUI_GLISSANDO__LAND_OUTLINES_H
#define GUI_GLISSANDO__LAND_OUTLINES_H

#include <cstdint>

namespace LandOutlines
{{

constexpr int RING_COUNT = {len(rings)};
constexpr int POINT_COUNT = {len(values) // 2};
constexpr double UNITS_PER_DEGREE = {SCALE}.0;

constexpr uint32_t RING_START[RING_COUNT + 1] = {{
{wrap(starts, 12)}
}};

constexpr int16_t POINTS[POINT_COUNT * 2] = {{
{wrap(values, 16)}
}};

}} // namespace LandOutlines

#endif // GUI_GLISSANDO__LAND_OUTLINES_H
"""


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("shapefile")
    parser.add_argument("--write", action="store_true", help="write LandOutlines.h rather than report")
    args = parser.parse_args()

    rings = [densified(ring) for ring in read_rings(args.shapefile)]
    text = header(rings)
    points = sum(len(ring) for ring in rings)
    print(f"{len(rings)} rings, {points} points, {len(text)} bytes of header", file=sys.stderr)
    if args.write:
        with open(OUT, "w") as f:
            f.write(text)
        print(f"wrote {os.path.normpath(OUT)}", file=sys.stderr)


if __name__ == "__main__":
    main()
