//=========================================================================
// Name:            HamTextTable.h
// Purpose:         The ham chat text table: phrases coded as one symbol, and
//                  the Huffman code length of every symbol.
//
// Generated by prototype/ham_table/gen_table.py from phrases.txt and
// chat_corpus.txt. Do not edit by hand: edit phrases.txt and run
//   python3 prototype/ham_table/gen_table.py --write
// Both ends of a contact need the same table, so any change here is a
// protocol change.
//=========================================================================

#ifndef TEXT_MESSAGING__HAM_TEXT_TABLE_H
#define TEXT_MESSAGING__HAM_TEXT_TABLE_H

#include <cstdint>

namespace TextMessaging
{
namespace HamText
{

// Matched exactly and case sensitively, longest first.
constexpr const char* PHRASES[] = {
    "CQ CQ",
    " the",
    " you",
};
constexpr int PHRASE_COUNT = 3;

// Symbols: printable ASCII 0x20-0x7E, PHRASES in order, ESC, EMPTY.
constexpr int SYMBOL_COUNT = 95 + PHRASE_COUNT + 2;
constexpr uint8_t SYMBOL_BITS[SYMBOL_COUNT] = {
     3, 10, 12, 13, 13, 11, 13, 10, 10, 10, 13, 12,  6,  8,  7, 10, //  !"#$%&'()*+,-./
     7,  7,  8,  8,  8,  8, 10,  7,  8,  8,  9, 11, 13, 12, 13,  8, // 0123456789:;<=>?
    13,  7,  8,  8,  9,  8,  9,  7,  8,  9,  9,  9,  9,  9,  9,  8, // @ABCDEFGHIJKLMNO
     8,  8,  8,  7,  7,  9, 10,  7,  9,  9, 10, 13, 13, 13, 13, 13, // PQRSTUVWXYZ[\]^_
    13,  4,  7,  6,  5,  4,  6,  6,  6,  4, 12,  7,  5,  6,  4,  4, // `abcdefghijklmno
     6, 10,  5,  4,  4,  6,  8,  7, 10,  7, 10, 13, 13, 13, 13, // pqrstuvwxyz{|}~
    11, // "CQ CQ" (spelled out: 35 bits)
     7, // " the" (spelled out: 17 bits)
     8, // " you" (spelled out: 20 bits)
    12, // ESC
    13, // EMPTY
};

} // namespace HamText
} // namespace TextMessaging

#endif // TEXT_MESSAGING__HAM_TEXT_TABLE_H
