//=========================================================================
// Name:            HamTextTable.h
// Purpose:         The ham chat text table: phrases coded as one symbol, and
//                  the Huffman code length of every symbol.
//
// Generated by prototype/ham_table/gen_table.py from phrases.txt and
// chat_corpus.txt. Do not edit by hand: edit phrases.txt and run
//   python3 prototype/ham_table/gen_table.py --write
// Both ends of a contact need the same table, so any change here is a
// protocol change.
//=========================================================================

#ifndef TEXT_MESSAGING__HAM_TEXT_TABLE_H
#define TEXT_MESSAGING__HAM_TEXT_TABLE_H

#include <cstdint>

namespace TextMessaging
{
namespace HamText
{

// Matched exactly and case sensitively, longest first.
constexpr const char* PHRASES[] = {
    "CQ CQ",
    " the",
    " you",
    " and",
    " to",
    " is",
    " for",
    " your",
    " with",
    " have",
    " here",
    " good",
    " very",
    " nice",
    "thanks",
    "Thanks",
    " name",
    " report",
    " copy",
    " signal",
    " weather",
    " today",
    " tonight",
    " rig",
    " pwr",
    " power",
    "qsy",
    " ant",
    "agn",
    " de",
    " pse",
    "fb",
    "73",
    " antenna",
    "ing",
    "in",
    "nd",
    " on",
    "es",
    "at",
    "tion",
    "re",
};
constexpr int PHRASE_COUNT = 42;

// Symbols: printable ASCII 0x20-0x7E, PHRASES in order, ESC, EMPTY.
constexpr int SYMBOL_COUNT = 95 + PHRASE_COUNT + 2;
constexpr uint8_t SYMBOL_BITS[SYMBOL_COUNT] = {
     3,  9, 11, 14, 13, 11, 13,  9, 10, 10, 13, 12,  6,  8,  6, 10, //  !"#$%&'()*+,-./
     6,  7,  8,  8,  8,  8,  9,  7,  8,  8,  9, 11, 13, 13, 13,  7, // 0123456789:;<=>?
    13,  7,  8,  7,  9,  8,  9,  7,  8,  8,  9,  8,  8,  8,  8,  8, // @ABCDEFGHIJKLMNO
     7,  8,  7,  7,  7,  8, 10,  7,  8,  8, 10, 13, 13, 13, 13, 13, // PQRSTUVWXYZ[\]^_
    13,  5,  7,  6,  6,  4,  6,  6,  6,  5, 12,  7,  5,  6,  5,  4, // `abcdefghijklmno
     6,  9,  5,  5,  5,  6,  8,  6, 10,  6,  9, 13, 13, 13, 13, // pqrstuvwxyz{|}~
    11, // "CQ CQ" (spelled out: 33 bits)
     7, // " the" (spelled out: 18 bits)
     8, // " you" (spelled out: 19 bits)
     9, // " and" (spelled out: 19 bits)
     8, // " to" (spelled out: 12 bits)
     7, // " is" (spelled out: 13 bits)
     8, // " for" (spelled out: 18 bits)
    10, // " your" (spelled out: 24 bits)
    10, // " with" (spelled out: 25 bits)
    10, // " have" (spelled out: 26 bits)
     8, // " here" (spelled out: 22 bits)
    10, // " good" (spelled out: 23 bits)
    10, // " very" (spelled out: 26 bits)
    10, // " nice" (spelled out: 23 bits)
    10, // "thanks" (spelled out: 33 bits)
    10, // "Thanks" (spelled out: 35 bits)
    10, // " name" (spelled out: 23 bits)
    10, // " report" (spelled out: 32 bits)
     9, // " copy" (spelled out: 25 bits)
     9, // " signal" (spelled out: 34 bits)
    10, // " weather" (spelled out: 38 bits)
    10, // " today" (spelled out: 29 bits)
    10, // " tonight" (spelled out: 39 bits)
    10, // " rig" (spelled out: 19 bits)
    10, // " pwr" (spelled out: 20 bits)
    10, // " power" (spelled out: 28 bits)
    10, // "qsy" (spelled out: 20 bits)
    10, // " ant" (spelled out: 18 bits)
    10, // "agn" (spelled out: 16 bits)
     8, // " de" (spelled out: 13 bits)
    10, // " pse" (spelled out: 18 bits)
    10, // "fb" (spelled out: 13 bits)
     9, // "73" (spelled out: 15 bits)
    10, // " antenna" (spelled out: 37 bits)
     7, // "ing" (spelled out: 16 bits)
     7, // "in" (spelled out: 10 bits)
     7, // "nd" (spelled out: 11 bits)
     8, // " on" (spelled out: 12 bits)
     7, // "es" (spelled out: 9 bits)
     7, // "at" (spelled out: 10 bits)
    10, // "tion" (spelled out: 19 bits)
     7, // "re" (spelled out: 9 bits)
    12, // ESC
    14, // EMPTY
};

} // namespace HamText
} // namespace TextMessaging

#endif // TEXT_MESSAGING__HAM_TEXT_TABLE_H
