"""Builds app/src/text_messaging/HamTextTable.h: the phrases and the code
lengths HamText codes chat text with.

Symbols: printable ASCII 0x20-0x7E, then the phrases of phrases.txt (each
coded as one symbol), then ESC (a raw byte follows) and EMPTY (the rest of
the block is padding). Character counts come from
chat_corpus.txt, 94 typical chat lines, blended 70/30 with the prose of the
repository's docs as of October 2026, so ordinary English is not punished
for missing from the small sample. EMPTY is forced to be the rarest symbol,
so the complemented canonical code gives it the all-zero codeword.

Text is split into symbols as the encoder splits it: at each character the
longest phrase that starts there, else the character itself.

    python3 gen_table.py            prints the table
    python3 gen_table.py --write    rewrites HamTextTable.h
"""
import re, heapq, collections, os, subprocess, sys, json
HERE=os.path.dirname(os.path.abspath(__file__))
ROOT=os.path.dirname(os.path.dirname(HERE))
msgs=[l.rstrip('\n') for l in open(os.path.join(HERE,'chat_corpus.txt')) if l.strip()]
# The docs as they stood when the table was built, so it can be rebuilt
# exactly whatever the docs say now.
DOCS_COMMIT='493f13a'
def at_commit(path):
    return subprocess.run(['git','-C',ROOT,'show',f'{DOCS_COMMIT}:{path}'],capture_output=True,text=True,check=True).stdout
names=subprocess.run(['git','-C',ROOT,'ls-tree','--name-only',DOCS_COMMIT,'docs/'],capture_output=True,text=True,check=True).stdout.split()
prose=''
for f in sorted(n for n in names if n.endswith('.md'))+['README.md']:
    t=at_commit(f)
    t=re.sub(r'```.*?```','',t,flags=re.S); t=re.sub(r'\(http[^)]*\)|\([^)]*\.(svg|md|png)[^)]*\)','',t)
    t=re.sub(r'[#*`|>_\[\]]','',t); t=re.sub(r'\s+',' ',t)
    prose+=t
prose=''.join(c for c in prose if 32<=ord(c)<127)
PHRASES=[json.loads(l) for l in open(os.path.join(HERE,'phrases.txt')) if l.strip() and not l.startswith('#')]
for p in PHRASES: assert len(p)>1 and all(32<=ord(c)<127 for c in p), p
assert len(set(PHRASES))==len(PHRASES)
NSYM=95+len(PHRASES)+2; ESC=NSYM-2; EOM=NSYM-1  # EOM is HamText's EMPTY
PHRASE_FLOOR=0.7/1000
BY_LENGTH=sorted(range(len(PHRASES)),key=lambda i:-len(PHRASES[i]))
def symbols(t):
    i=0
    while i<len(t):
        for k in BY_LENGTH:
            if t.startswith(PHRASES[k],i): yield 95+k; i+=len(PHRASES[k]); break
        else: yield ord(t[i])-32; i+=1
def counts(texts, weight):
    c=collections.Counter(); n=0
    for t in texts:
        for s in symbols(t): c[s]+=1; n+=1
    return {k:v*weight/n for k,v in c.items()}
def lengths_for(train_msgs, maxlen=15):
    f=[1e-4]*NSYM
    for src,w in ((counts(train_msgs,0.7),1),(counts([prose],0.3),1)):
        for k,v in src.items(): f[k]+=v
    # A listed phrase the small corpus rarely or never uses is still
    # expected on the air (fb, qsy, agn): count it as at least about once
    # per 30 chat lines, so its code stays shorter than spelling it out.
    for k in range(len(PHRASES)): f[95+k]=max(f[95+k],PHRASE_FLOOR)
    f[ESC]=2e-4
    f[EOM]=min(f)/2
    while True:
        h=[(f[i],i,(i,)) for i in range(NSYM)]; heapq.heapify(h); L=[0]*NSYM; k=NSYM
        while len(h)>1:
            a=heapq.heappop(h); b=heapq.heappop(h)
            for s in a[2]+b[2]: L[s]+=1
            heapq.heappush(h,(a[0]+b[0],k,a[2]+b[2])); k+=1
        if max(L)<=maxlen: break
        f=[x**0.9 for x in f]; f[EOM]=min(f[:EOM])/2
    assert abs(sum(2**-l for l in L)-1)<1e-12
    assert L[EOM]==max(L)
    return L
def spelled(L,p): return sum(L[ord(c)-32] for c in p)
def header(L):
    rows=[]
    for i in range(0,95,16):
        rows.append('    '+', '.join(f'{x:2d}' for x in L[i:min(i+16,95)])+','+' // '+''.join(chr(32+j) for j in range(i,min(i+16,95))))
    for k,p in enumerate(PHRASES):
        rows.append(f'    {L[95+k]:2d}, // {json.dumps(p)} (spelled out: {spelled(L,p)} bits)')
    rows.append(f'    {L[ESC]:2d}, // ESC')
    rows.append(f'    {L[EOM]:2d}, // EMPTY')
    phrases=''.join(f'    {json.dumps(p)},\n' for p in PHRASES)
    return f"""//=========================================================================
// Name:            HamTextTable.h
// Purpose:         The ham chat text table: phrases coded as one symbol, and
//                  the Huffman code length of every symbol.
//
// Generated by prototype/ham_table/gen_table.py from phrases.txt and
// chat_corpus.txt. Do not edit by hand: edit phrases.txt and run
//   python3 prototype/ham_table/gen_table.py --write
// Both ends of a contact need the same table, so any change here is a
// protocol change.
//=========================================================================

#ifndef TEXT_MESSAGING__HAM_TEXT_TABLE_H
#define TEXT_MESSAGING__HAM_TEXT_TABLE_H

#include <cstdint>

namespace TextMessaging
{{
namespace HamText
{{

// Matched exactly and case sensitively, longest first.
constexpr const char* PHRASES[] = {{
{phrases}}};
constexpr int PHRASE_COUNT = {len(PHRASES)};

// Symbols: printable ASCII 0x20-0x7E, PHRASES in order, ESC, EMPTY.
constexpr int SYMBOL_COUNT = 95 + PHRASE_COUNT + 2;
constexpr uint8_t SYMBOL_BITS[SYMBOL_COUNT] = {{
""" + '\n'.join(rows) + """
};

} // namespace HamText
} // namespace TextMessaging

#endif // TEXT_MESSAGING__HAM_TEXT_TABLE_H
"""
if __name__=='__main__':
    L=lengths_for(msgs)
    for k,p in enumerate(PHRASES):
        assert L[95+k]<spelled(L,p), f'{p!r} costs {L[95+k]} bits, no less than spelled out'
    print('max',max(L),'EOM',L[EOM],'ESC',L[ESC])
    print(''.join(f"{chr(32+i)}:{L[i]} " for i in range(95) if L[i]<=6))
    for k,p in enumerate(PHRASES): print(f'{p!r}: {L[95+k]} bits (spelled out {spelled(L,p)})')
    if '--write' in sys.argv:
        out=os.path.join(ROOT,'app','src','text_messaging','HamTextTable.h')
        open(out,'w').write(header(L)); print('wrote',out)
