"""Generates the golden data the Glissando C++ tests compare against, from
the NumPy prototype (https://github.com/baitisj/glissando, prototype/).

    python3 make_vectors.py [/path/to/prototype]

Writes, next to this script:
  GlissandoVectors.h    CRC and coded bits of a few payloads, and spread
                        samples plus whole-signal statistics of G4 and G5
                        transmissions
  python_g4_clip.raw    one G4 transmission through the prototype's channel
                        model (lead-in, frequency offset, AWGN), int16 LE
"""
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "../../prototype"))

import channel as ch  # noqa: E402
import fec  # noqa: E402
import glissando as g  # noqa: E402

STRIDE = 29  # every 29th sample of a transmission (prime, so every sample phase of a symbol is hit)


def bits(a):
    return "".join(str(int(b)) for b in a)


def payloads():
    rng = np.random.default_rng(1234)
    return {
        "zeros": np.zeros(77, dtype=int),
        "ones": np.ones(77, dtype=int),
        "alternating": np.arange(77) % 2,
        "random1": rng.integers(0, 2, 77),
        "random2": rng.integers(0, 2, 77),
        "random3": rng.integers(0, 2, 77),
    }


def main():
    p = payloads()
    out = []
    out.append("// Generated by make_vectors.py from the Glissando NumPy prototype. Do not edit.")
    out.append("#ifndef GLISSANDO__TEST_VECTORS_H")
    out.append("#define GLISSANDO__TEST_VECTORS_H")
    out.append("")
    out.append("namespace GlissandoVectors")
    out.append("{")
    out.append("")
    out.append("struct FecVector")
    out.append("{")
    out.append("    const char* name;")
    out.append("    const char* payload;    // 77 bits")
    out.append("    const char* crc;        // 14 bits")
    out.append("    const char* coded;      // 195 bits, fec.encode_frame()")
    out.append("};")
    out.append("")
    out.append("const FecVector FEC[] = {")
    for name, pl in p.items():
        out.append(f'    {{"{name}", "{bits(pl)}",')
        out.append(f'     "{bits(fec.crc14(list(pl)))}",')
        out.append(f'     "{bits(fec.encode_frame(pl))}"}},')
    out.append("};")
    out.append("")

    for gi, pls in ((4, [p["random1"]]), (5, [p["random1"], p["random2"]])):
        x = g.transmit(pls, g.GEARS[gi])
        spread = x[::STRIDE]
        out.append(f"// g.transmit() for G{gi}: payload(s) {', '.join(n for n, v in p.items() if any(v is q for q in pls))}")
        out.append(f"constexpr int G{gi}_LENGTH = {len(x)};")
        out.append(f"constexpr double G{gi}_RMS = {np.sqrt(np.mean(x ** 2)):.9f};")
        out.append(f"constexpr double G{gi}_MEAN = {np.mean(x):.9e};")
        out.append(f"const float G{gi}_SPREAD[] = {{ // x[::{STRIDE}]")
        for i in range(0, len(spread), 10):
            out.append("    " + ", ".join(f"{v:.6f}f" for v in spread[i:i + 10]) + ",")
        out.append("};")
        out.append("")
    out.append(f"constexpr int SPREAD_STRIDE = {STRIDE};")
    out.append("")

    # A G4 clip through the prototype's channel: lead-in, frequency offset
    # and AWGN about 4 dB above the prototype's 50 % threshold (-17.4 dB).
    rng = np.random.default_rng(0x6C1F)
    gear = g.GEARS[4]
    pl = p["random3"]
    x = g.transmit([pl], gear)
    lead, tail, df, snr = int(0.37 * g.FS), int(0.25 * g.FS), 7.3, -13.5
    buf = np.concatenate([np.zeros(lead), x, np.zeros(tail)])
    buf = ch.freq_shift(buf, df)
    buf = ch.add_noise(buf, snr, rng, np.mean(x ** 2))
    scale = 32767 / (1.05 * np.max(np.abs(buf)))
    clip = np.round(buf * scale).astype("<i2")
    clip.tofile(os.path.join(HERE, "python_g4_clip.raw"))
    res = g.receive(clip.astype(float), gear)
    assert res[0][0] is not None and np.array_equal(res[0][0], pl), "prototype failed to decode its own clip"
    rep = res[0][1]
    out.append("// python_g4_clip.raw: G4, payload random3, int16 little endian.")
    out.append(f"constexpr int CLIP_SAMPLES = {len(clip)};")
    out.append(f"constexpr int CLIP_START = {lead};")
    out.append(f"constexpr double CLIP_OFFSET_HZ = {df};")
    out.append(f"constexpr double CLIP_SNR_DB = {snr};")
    out.append(f"// The prototype decodes it at start {rep['start']}, {rep['df']:.3f} Hz, "
               f"reporting SNR {rep['snr_db']:.2f} dB.")
    out.append(f"constexpr int CLIP_PROTOTYPE_START = {rep['start']};")
    out.append(f"constexpr double CLIP_PROTOTYPE_SNR_DB = {rep['snr_db']:.3f};")
    out.append("")
    out.append("} // namespace GlissandoVectors")
    out.append("")
    out.append("#endif // GLISSANDO__TEST_VECTORS_H")
    with open(os.path.join(HERE, "GlissandoVectors.h"), "w") as f:
        f.write("\n".join(out) + "\n")
    print("clip:", len(clip), "samples; prototype report", rep)


if __name__ == "__main__":
    main()
